### ISSUE TITLE
Printing Reports

### ISSUE THREAD

**Issue by bentech** [aschenkels-ictstudio/openerp-install-scripts#11]
Hi,

When printing reports you get the error on fresh install of ubuntu 14.04
"Report
Unable to find Wkhtmltopdf on this system. The report will be shown in html."

To fix this issue:

wget http://sourceforge.net/projects/wkhtmltopdf/files/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
cp /usr/local/bin/wkhtmltopdf /usr/bin
cp /usr/local/bin/wkhtmltoimage /usr/bin

**Comment by aschenkels-ictstudio** [comment]
Stuff has been added to the script
