### ISSUE TITLE
Wkhtmltopdf inside script

### ISSUE THREAD

**Issue by Yenthe666** [aschenkels-ictstudio/openerp-install-scripts#12]
Hey André

First of all, that is one amazing script. I'd love to add automatic install for Wkhtmltopdf though.
If you'd like to test it out, i've put the code up.
Another option would be to add a parameter on top which you can set on true/false as user to choose if you want to install Wkhtmltopdf or not. I'm not sure which would be best..

AUTOMATIC INSTALL SCRIPT:
#--------------------------------------------------
#Adding WKHTMLTOPDF
#--------------------------------------------------
echo -e "\n---- Install WkHtmlToPdf 0.12.1 ----"
sudo wget -P Downloads http://sourceforge.net/projects/wkhtmltopdf/files/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
cd Downloads
sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
cd /usr/local/bin
sudo cp wkhtmltoimage /usr/bin/wkhtmltoimage
sudo cp wkhtmltopdf /usr/bin/wkhtmltopdf

USER CAN CHOOSE YES OR NO:
#Set this to True if you want to install Wkhtmlopdf. False if you do not want
#it installed.
wkhtmltoPdf='True'

if [[ $wkhtmltoPdf  = "True" ]]; then
    echo -e "\n---- Install WkHtmlToPdf 0.12.1 ----"
    sudo wget -P Downloads http://sourceforge.net/projects/wkhtmltopdf/files/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
    cd Downloads
    sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
    cd /usr/local/bin
    sudo cp wkhtmltoimage /usr/bin/wkhtmltoimage
    sudo cp wkhtmltopdf /usr/bin/wkhtmltopdf
    echo -e "Starting up Odoo!"
else
    echo -e "\n---- User doesn't want WkHtmlToPdf ----"
fi;

**Comment by aschenkels-ictstudio** [comment]
The wkhtml 2 pdf is added to the script.

**Comment by Yenthe666** [comment]
Perfect! Thanks @aschenkels-ictstudio
